name: turbonova_game_booster
description: A powerful mobile game booster.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^10.0.1
  battery_plus: ^5.0.0

flutter:
  uses-material-design: true
